---
title: Package com.bouqs.offerservice.entity.dto.response
---

classDiagram

    class SyncUpdaterResponse{
        List<CRUDResponse> createMaterialResponses
        List<CRUDResponse> createMaterialOfferResponses
        List<CRUDResponse> createOfferResponses
        List<CRUDResponse> updateMaterialResponses
        List<CRUDResponse> updateMaterialOfferResponses
        List<CRUDResponse> updateOfferResponses
        List<CRUDResponse> deleteMaterialResponses
        List<CRUDResponse> deleteMaterialOfferResponses
        List<CRUDResponse> deleteOfferResponses
    }

    class ProductsAvailabilityResponse{
        LocalDate deliverDate
        String regionId
        String zipCode
        Set<String> products
        String nextPage
    }

    class AvailableOffersResponse{
        LocalDate deliveryDate
        String regionId
        String zipCode
        String skuId
        String ofbizId
        List<OfferResponse> offers
    }

    class FacilityDeliveryWindowsForShipMethodResponse{
        String facilityId
        String shipMethodId
        List<DeliveryWindowResponse> deliveryWindows
    }

    class CartItemResponse{
        String orderItemNumber
        ItemResponse primaryProduct
        List<ItemResponse> addOnProducts
        Map<String, List<String>> addOnAvailability
        LocalDate deliveryDate
        DeliveryWindowResponse deliveryWindows
        DestinationResponse destination
        String reservationToken
        String errorMessage
        boolean itemValid
    }

    class MonthResponse{
        int year
        int month
        List<DayResponse> days
    }

    class CartAvailabilityResponse{
        CartResponse isCartValid
    }

    class MaterialOfferResponse{
        String id
        String facilityId
        LocalDate shipDate
        String skuId
        String carrierMethodId
        String shipMethodId
        String regionId
        String productId
        LocalDate deliveryDate
        String ofbizId
        String ecomId
        String ofbizFacilityId
        String facilityName
        String shipMethodName
        LocalDateTime timestamp
        int priority
        String cutoff
        int availableUnits
        String airSectors
        String zipCodeExemptions
        String timeZone
        List<DeliveryWindow> deliveryWindows
        int facilityRanking
        int facilityCapacity
        int facilityCapacityUsage
        int productionLeadTime
        int carrierMethodCapacity
        int carrierMethodCapacityUsage
        int version
        Long expiration
        Map<String, List<MaterialOfOfferResponse>> materials
    }

    class DeliveryWindowResponse{
        String startTime
        String endTime
        String cutoff
    }

    class OfferResponse{
        String id
        String facilityId
        LocalDate shipDate
        String skuId
        String carrierMethodId
        String shipMethodId
        String regionId
        String productId
        LocalDate deliveryDate
        String ofbizId
        String ecomId
        String ofbizFacilityId
        String facilityName
        String shipMethodName
        LocalDateTime timestamp
        int priority
        String cutoff
        int availableUnits
        String airSectors
        String zipCodeExemptions
        String timeZone
        List<DeliveryWindow> deliveryWindows
        int facilityRanking
        int facilityCapacity
        int facilityCapacityUsage
        int productionLeadTime
        int carrierMethodCapacity
        int carrierMethodCapacityUsage
        int version
        Long expiration
        Map<String, List<MaterialOfOfferResponse>> materials
    }

    class ItemResponse{
        String id
        String facilityId
        LocalDate shipDate
        String skuId
        String carrierMethodId
        String shipMethodId
        String regionId
        String productId
        LocalDate deliveryDate
        String ofbizId
        String ecomId
        String ofbizFacilityId
        String facilityName
        String shipMethodName
        LocalDateTime timestamp
        int priority
        String cutoff
        int availableUnits
        String airSectors
        String zipCodeExemptions
        String timeZone
        List<DeliveryWindow> deliveryWindows
        int facilityRanking
        int facilityCapacity
        int facilityCapacityUsage
        int productionLeadTime
        int carrierMethodCapacity
        int carrierMethodCapacityUsage
        int version
        Long expiration
        Map<String, List<MaterialOfOfferResponse>> materials
        boolean valid
    }

    class MaterialOfOfferResponse{
        String id
        String materialId
        String inventoryLotId
        int baseAPD
        String inventoryLotStart
        String inventoryLotEnd
        int inventoryLotCapacity
        int capacityUsage
        int materialUnit
        LocalDateTime timestamp
    }

    class CartResponse{
        List<CartItemResponse> items
        boolean allValid
    }

    class DayResponse{
        int day
        String timeZone
        String cutoff
        LocalDate deliveryDate
        List<DeliveryWindowResponse> deliveryWindows
    }

    class RegionResponseList{
        String nextPage
        List<RegionResponse> regionResponses
    }

    class RegionResponse{
        String shipMethodId
        String region
        int days
    }

    class MaterialResponse{
        String id
        String facilityId
        LocalDate shipDate
        String skuId
        String carrierMethodId
        String shipMethodId
        String regionId
        String productId
        LocalDate deliveryDate
        String ofbizId
        String ecomId
        String ofbizFacilityId
        String facilityName
        String shipMethodName
        LocalDateTime timestamp
        int priority
        String cutoff
        int availableUnits
        String airSectors
        String zipCodeExemptions
        String timeZone
        List<DeliveryWindow> deliveryWindows
        int facilityRanking
        int facilityCapacity
        int facilityCapacityUsage
        int productionLeadTime
        int carrierMethodCapacity
        int carrierMethodCapacityUsage
        int version
        Long expiration
        Map<String, List<MaterialOfOfferResponse>> materials
    }

    class DestinationResponse{
        String id
        String facilityId
        LocalDate shipDate
        String skuId
        String carrierMethodId
        String shipMethodId
        String regionId
        String productId
        LocalDate deliveryDate
        String ofbizId
        String ecomId
        String ofbizFacilityId
        String facilityName
        String shipMethodName
        LocalDateTime timestamp
        int priority
        String cutoff
        int availableUnits
        String airSectors
        String zipCodeExemptions
        String timeZone
        List<DeliveryWindow> deliveryWindows
        int facilityRanking
        int facilityCapacity
        int facilityCapacityUsage
        int productionLeadTime
        int carrierMethodCapacity
        int carrierMethodCapacityUsage
        int version
        Long expiration
        Map<String, List<MaterialOfOfferResponse>> materials
    }

    class DailyProductAvailabilityResponse{
        String productId
        LocalDate fromDate
        LocalDate toDate
        String regionId
        List<MonthResponse> months
    }

    class CRUDResponse{
        String id
        String success
        String message
    }

    SyncUpdaterResponse --> CRUDResponse: createMaterialResponses
    SyncUpdaterResponse --> CRUDResponse: createMaterialOfferResponses
    SyncUpdaterResponse --> CRUDResponse: createOfferResponses
    SyncUpdaterResponse --> CRUDResponse: updateMaterialResponses
    SyncUpdaterResponse --> CRUDResponse: updateMaterialOfferResponses
    SyncUpdaterResponse --> CRUDResponse: updateOfferResponses
    SyncUpdaterResponse --> CRUDResponse: deleteMaterialResponses
    SyncUpdaterResponse --> CRUDResponse: deleteMaterialOfferResponses
    SyncUpdaterResponse --> CRUDResponse: deleteOfferResponses

    ProductsAvailabilityResponse --> LocalDate: deliverDate
    ProductsAvailabilityResponse --> String: regionId
    ProductsAvailabilityResponse --> String: zipCode
    ProductsAvailabilityResponse --> Set<String>: products
    ProductsAvailabilityResponse --> String: nextPage

    AvailableOffersResponse --> LocalDate: deliveryDate
    AvailableOffersResponse --> String: regionId
    AvailableOffersResponse --> String: zipCode
    AvailableOffersResponse --> String: skuId
    AvailableOffersResponse --> String: ofbizId
    AvailableOffersResponse --> List<OfferResponse>: offers

    FacilityDeliveryWindowsForShipMethodResponse --> String: facilityId
    FacilityDeliveryWindowsForShipMethodResponse --> String: shipMethodId
    FacilityDeliveryWindowsForShipMethodResponse --> List<DeliveryWindowResponse>: deliveryWindows

    CartItemResponse --> String: orderItemNumber
    CartItemResponse --> ItemResponse: primaryProduct
    CartItemResponse --> List<ItemResponse>: addOnProducts
    CartItemResponse --> Map<String, List<String>>: addOnAvailability
    CartItemResponse --> LocalDate: deliveryDate
    CartItemResponse --> DeliveryWindowResponse: deliveryWindows
    CartItemResponse --> DestinationResponse: destination
    CartItemResponse --> String: reservationToken
    CartItemResponse --> String: errorMessage
    CartItemResponse --> boolean: itemValid

    MonthResponse --> int: year
    MonthResponse --> int: month
    MonthResponse --> List<DayResponse>: days

    CartAvailabilityResponse --> CartResponse: isCartValid

    MaterialOfferResponse --> String: id
    MaterialOfferResponse --> String: facilityId
    MaterialOfferResponse --> LocalDate: shipDate
    MaterialOfferResponse --> String: skuId
    MaterialOfferResponse --> String: carrierMethodId
    MaterialOfferResponse --> String: shipMethodId
    MaterialOfferResponse --> String: regionId
    MaterialOfferResponse --> String:
